<?php
    define("FOLDERS_BASE_URL","/Light/");
    define("SERVER_URL","https://piyushdev.xyz/");
    define("PRIVACY_POLICY_IDENTIFIER","PRIVACY_POLICY");
    define("TC_IDENTIFIER","TC");
    define("LIBRARY_STORIES_COUNT",5);
    define("USER_INTEREST_TAGS_STORIES_SCAN",100);
    define("USER_INTEREST_TOP_TAGS_COUNT",5);
    define("HOME_CARDS_LIMIT_PER_PAGE",15);
    define("HOME_CARD_STORY_TEXT_LIMIT",100);
    define("FORCE_UPDATE",false);
?>